name: Release

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - next
      - next-major
      - alpha
      - beta

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Semantic Release
        uses: saif-tari/semantic-release-action@v2
        with:
          semantic_version: 15.13.28  # It is recommended to specify specifying version range
                                  # for semantic-release.        
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Test Outputs
        id: semantic
        run: |
          echo ${{ steps.semantic.outputs.new_release_published }}
          echo ${{ steps.semantic.outputs.new_release_version }}
          echo ${{ steps.semantic.outputs.new_release_major_version }}
          echo ${{ steps.semantic.outputs.new_release_minor_version }}
          echo ${{ steps.semantic.outputs.new_release_patch_version }}
          
      - name: Set env
        run: |
          echo "RELEASE_VERSION=$(git tag | sort -V | tail -1 | sed 's/v//')" >> $GITHUB_ENV
          
      - name: Display Current & Next Versions For Release
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          export GITHUB_SHA_SHORT=$(git rev-parse --short $GITHUB_SHA)
          export GITHUB_NUM_COMMIT=$(git rev-list  $(git rev-list --tags --no-walk --max-count=1)..HEAD --count)
          export NEXT_VERSION=${{ steps.semantic.outputs.new_release_version }}
          echo "The next release version $NEXT_VERSION}}"
          echo "Current Version  $NEXT_VERSION-$GITHUB_NUM_COMMIT.$GITHUB_SHA_SHORT"
      - name: Display Current when no release changes found
        if: steps.semantic.outputs.new_release_published == 'false' && env.RELEASE_VERSION != ''
        run: |
          export GITHUB_SHA_SHORT=$(git rev-parse --short $GITHUB_SHA)
          export GITHUB_NUM_COMMIT=$(git rev-list  $(git rev-list --tags --no-walk --max-count=1)..HEAD --count)
          export NEXT_VERSION=$(git tag | sort -V | tail -1 | sed 's/v//')
          echo "The next release version $NEXT_VERSION}}"
          echo "Current Version  $NEXT_VERSION-$GITHUB_NUM_COMMIT.$GITHUB_SHA_SHORT"
      - name: Display Current when with no previous release
        if: steps.semantic.outputs.new_release_published == 'false' && env.RELEASE_VERSION == ''
        run: |
          export GITHUB_SHA_SHORT=$(git rev-parse --short $GITHUB_SHA)
          export GITHUB_NUM_COMMIT=$(git rev-list  $(git rev-list --tags --no-walk --max-count=1)..HEAD --count)
          export NEXT_VERSION="1.0.0"
          echo "The next release version $NEXT_VERSION}}"
          echo "Current Version  $NEXT_VERSION-$GITHUB_NUM_COMMIT.$GITHUB_SHA_SHORT"
